In [1]:
# introduction to Python Advanced Topics

In [ ]:
# installation of Intellij IDEA

1.  Download Intelliji IDEA from jetbrains official site
    https://www.jetbrains.com/idea/download/#section=windows
    
2.  download the installation file as per your Operating system

3.  in windows -> click next -> next -- next

4.  add the Path variable

5. once the Intelliji is installed you can see it in the start --> open it and create the project

6. configure the python -> go to configure --> plugins --> in search bar type "python community edition"

7. click on install--> once install restart the application once to get synced.


In [2]:
Creation of new project in Intelij

--> open intellij --> create new project --> select the SDK as Python.


SyntaxError: invalid syntax (<ipython-input-2-7c525bc5e511>, line 1)

In [ ]:
# install of numpy

In [3]:
!pip install numpy

In [4]:
!pip install numpy --upgrade

  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5


In [ ]:
# Numpy Introduction 

Numpy is considered as fundamental package of scitific computing in python.
it has wide and high end variety of mathematical operations
it is working with N dimensional arrays *** which is making super fast in processig and computing capabilities.

In [ ]:
# Introduction to creating arrays


In [6]:
import numpy as np

In [8]:
array_one =np.array([1,2,3,4,5,6])
array_one

array([1, 2, 3, 4, 5, 6])

In [9]:
type(array_one)

numpy.ndarray

In [10]:
numbers=[9,8,7,6,5]

In [11]:
array_two =np.array(numbers)
array_two

array([9, 8, 7, 6, 5])

In [13]:
array_of_zeros =np.zeros((3,4))
array_of_zeros  #here we are using inbuilt function called zero matrix
# numpy by default number as float so that we have 0.(dot)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])